sudo: false
language: python
python:
  - "3.6"
  - "3.7"
dist: xenial  # needed for py37
cache: pip

services:
  - postgresql

addons:
  postgresql: '9.6'

env:
  DATABASE_ENGINE=postgresql
  DATABASE_NAME=test
  DATABASE_USER=kokuadmin
  DATABASE_HOST=localhost
  DATABASE_PORT=5432
  DATABASE_PASSWORD=''

before_install:
  - export BOTO_CONFIG=/dev/null
  - sudo rm -f /etc/boto.cfg
install:
    - pip install tox-travis codecov

before_script:
  - psql -c "create database ${DATABASE_NAME};" -U postgres

script:
    - tox

after_success:
    - codecov
