sudo: false
language: python
python:
  - "3.6"
cache: pip

services:
  - postgresql

addons:
  postgresql: '9.6'

env:
  DATABASE_ENGINE=postgresql
  DATABASE_NAME=test
  DATABASE_USER=kokuadmin
  DATABASE_HOST=localhost
  DATABASE_PORT=5432
  DATABASE_PASSWORD=''

before_install:
  - export BOTO_CONFIG=/dev/null
install:
    - pip install tox codecov

script:
    - tox

after_success:
    - codecov
