version: '3'
services:
  rabbit:
      hostname: rabbit
      image: rabbitmq:latest
      environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest
      ports:
          - "${RABBITMQ_PORT-5673}:5672"

  masu-server:
      build:
          context: .
          dockerfile: Dockerfile
      working_dir: /masu
      entrypoint: 'flask run --host 0.0.0.0'
      environment:
        - DATABASE_ENGINE=postgresql
        - DATABASE_NAME=${DATABASE_NAME-postgres}
        - DATABASE_HOST=db
        - DATABASE_PORT=5432
        - DATABASE_USER=${DATABASE_USER-postgres}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD-postgres}
        - RABBITMQ_HOST=rabbit
        - RABBITMQ_PORT=5672
        - MASU_SECRET_KEY=abc
        - OPENSHIFT_BUILD_COMMIT=blah
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - FLASK_APP=masu
        - FLASK_ENV=development
        - prometheus_multiproc_dir=/tmp
        - MASU_DATE_OVERRIDE
        - MASU_RETAIN_NUM_MONTHS
        - MASU_DEBUG
      privileged: true
      ports:
          - "5000:5000"
      volumes:
        - '.:/masu/'
      links:
        - rabbit

  masu-worker:
      build:
          context: .
          dockerfile: Dockerfile
      working_dir: /masu
      entrypoint: ['celery', 'worker', '-A', 'masu.celery.worker', '-l', 'debug', '-B', '--broker=amqp://guest:guest@rabbit:5672//', '-Q', 'celery,download,process,remove_expired', '--loglevel=INFO']
      environment:
        - DATABASE_ENGINE=postgresql
        - DATABASE_NAME=${DATABASE_NAME-postgres}
        - DATABASE_HOST=db
        - DATABASE_PORT=5432
        - DATABASE_USER=${DATABASE_USER-postgres}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD-postgres}
        - MASU_SECRET_KEY=abc
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - INSIGHTS_KAFKA_HOST=kafka
        - INSIGHTS_KAFKA_PORT=29092
        - KAFKA_CONNECT=True
        - prometheus_multiproc_dir=/tmp
        - MASU_DATE_OVERRIDE
        - MASU_RETAIN_NUM_MONTHS
        - MASU_DEBUG
      privileged: true
      ports:
          - "9999:9999"
      volumes:
        - '.:/masu/'
        # - '~/aws_local:/tmp/local_bucket'
        # - '~/insights_local:/var/tmp/insights_local'
      links:
          - rabbit
      depends_on:
          - rabbit

  prometheus:
      hostname: prometheus
      image: prom/prometheus:latest
      ports:
          - "9090:9090"
      volumes:
        - './docker_resources/prometheus/:/etc/prometheus/'

  grafana:
      image: grafana/grafana
      ports:
          - "3000:3000"
      volumes:
        - './docker_resources/grafana/provisioning/:/etc/grafana/provisioning/'
      depends_on:
        - prometheus

  monitor:
      build:
          context: .
          dockerfile: Dockerfile
      working_dir: /masu
      entrypoint: ['celery-prometheus-exporter', '--enable-events', '--broker=amqp://rabbit:5672//', '--verbose']
      privileged: true
      ports:
          - "8888:8888"
      volumes:
        - '.:/masu/'
      links:
          - rabbit
      depends_on:
          - rabbit

networks:
  default:
    external:
      name: koku-network
