kind: Template
apiVersion: v1
metadata:
  name: masu-configmap-template
  annotations:
    openshift.io/display-name: "Masu"
    description: "Configuration for data ingestion engine for Koku"
    tags: "python,flask"
    iconClass: "icon-python"
    openshift.io/long-description: "This template defines resources needed to run the Masu application, including a build configuration and an application deployment configuration."
    openshift.io/provider-display-name: "Red Hat, Inc."
    openshift.io/documentation-url: "https://koku.readthedocs.io/en/latest/"
labels:
  app: masu
  template: masu-template
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: ${NAME}
    labels:
      name: ${NAME}
  data:
    database-engine: postgresql
    database-name: koku
    database-service-name: POSTGRES_SQL
    postgres-sql-service-host: ${DATABASE_SERVICE_NAME}.${NAMESPACE}.svc
    postgres-sql-service-port: "5432"
    app-config: /opt/app-root/src/masu/gunicorn.py
    app-home: /opt/app-root/src/masu
    app-module: masu.__init__:create_app()
    app-namespace: ${NAMESPACE}
    rabbitmq-host: rabbitmq.${NAMESPACE}.svc
    insights-kafka-server-host: ${KAFKA_HOST}.${KAFKA_NAMESPACE}.svc
    insights-kafka-server-port: ${KAFKA_PORT}
    insights-kafka-conn-retry-interval: ${KAFKA_TIMEOUT_SECONDS}
    log-level: INFO
    worker-queues: "celery,download,remove_expired,reporting"
    schedule-report-checks: "True"
    schedule-check-interval: "60"
    remove-expired-data-on-day: "1"
    remove-expired-data-utc-time: "00:00"
    prometheus-dir: ${PROMETHEUS_DIR}
    date-override: ""
    retain-num-months: "3"
    remove-expired-report-data-on-day: "1"
    remove-expired-report-utc-time: "00:00"
    initial-ingest-num-months: "2"
    initial-ingest-override: "False"
    debug: "False"
    kafka-connect: "True"
parameters:
- description: The name assigned to all frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: masu
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: myproject
- description: Database Service Name
  displayName: Database Service Name
  name: DATABASE_SERVICE_NAME
  required: true
  value: koku-pgsql
- description: Insights Upload Server address
  displayName: Kafka server address
  name: KAFKA_HOST
  required: true
  value: localhost
- description: Insights Upload Server namespace
  displayName: Kafka server namespace
  name: KAFKA_NAMESPACE
  required: true
  value: myproject
- description: Insights Upload Server port
  displayName: Kafka server port
  name: KAFKA_PORT
  required: true
  value: "29092"
- description: Insights Upload Server Connection Retry Interval
  displayName: Kafka server reconnect timeout
  name: KAFKA_TIMEOUT_SECONDS
  required: true
  value: "30"
- description: Directory for Prometheus metrics.
  displayName: Masu Prometheus metrics directory
  name: PROMETHEUS_DIR
  required: true
  value: '/tmp'
