kind: Template
apiVersion: v1
metadata:
  name: masu-monitor-template
  annotations:
    openshift.io/display-name: "Masu"
    description: "Prometheus monitor for data ingestion engine for Koku"
    tags: "python,celery,prometheus"
    iconClass: "icon-python"
    openshift.io/long-description: "This template defines resources needed to run the Masu application, including a build configuration and an application deployment configuration."
    openshift.io/provider-display-name: "Red Hat, Inc."
    openshift.io/documentation-url: "https://koku.readthedocs.io/en/latest/"
labels:
  app: ${NAME}
  template: ${NAME}-monitor-template
objects:
- kind: Service
  apiVersion: v1
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    name: ${NAME}-monitor
    labels:
      app: ${NAME}
  spec:
    ports:
    - name: 8888-tcp
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      name: ${NAME}-monitor
- kind: BuildConfig
  apiVersion: v1
  metadata:
    annotations:
      description: Defines how to build the application
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}-monitor
    labels:
      app: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-monitor:latest
    resources:
      requests:
        memory: ${BUILD_MEMORY_REQUEST}
      limits:
        memory: ${BUILD_MEMORY_LIMIT}
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: PIP_INDEX_URL
            value: ${PIP_INDEX_URL}
          - name: PIPENV_PYPI_MIRROR
            value: ${PIPENV_PYPI_MIRROR}
          - name: ENABLE_PIPENV
            value: "true"
          - name: UPGRADE_PIP_TO_LATEST
            value: ""
          - name: APP_CONFIG
            valueFrom:
              configMapKeyRef:
                name: ${NAME}
                key: app-config
                optional: false
          - name: APP_HOME
            valueFrom:
              configMapKeyRef:
                name: ${NAME}
                key: app-home
          - name: APP_MODULE
            valueFrom:
              configMapKeyRef:
                name: ${NAME}
                key: app-module
        from:
          kind: ImageStreamTag
          name: python-36-centos7:latest
          namespace: ${NAMESPACE}
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    annotations:
      description: Defines how to deploy the celery monitor
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}-monitor
    labels:
      app: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}-monitor
    resources:
      requests:
        cpu: ${CELERY_MONITOR_CPU_REQUEST}
        memory: ${CELERY_MONITOR_MEMORY_REQUEST}
      limits:
        cpu: ${CELERY_MONITOR_CPU_LIMIT}
        memory: ${CELERY_MONITOR_MEMORY_LIMIT}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${NAME}-monitor
        name: ${NAME}-monitor
      spec:
        containers:
        - name: ${NAME}-monitor
          image: ${NAME}-monitor
          ports:
            - containerPort: 8888
              protocol: TCP
          command:
            - /bin/bash
            - -c
            - >
              PYTHONPATH=. scl enable rh-python36 --
              celery-prometheus-exporter --enable-events --broker=amqp://${RABBITMQ_HOST}:5672// --verbose
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}
                  key: rabbitmq-host
                  optional: false
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}
                  key: log-level
                  optional: false
          resources:
            requests:
              cpu: ${CELERY_MONITOR_CPU_REQUEST}
              memory: ${CELERY_MONITOR_MEMORY_REQUEST}
            limits:
              cpu: ${CELERY_MONITOR_CPU_LIMIT}
              memory: ${CELERY_MONITOR_MEMORY_LIMIT}
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - ${NAME}-monitor
        from:
          kind: ImageStreamTag
          name: ${NAME}-monitor:latest
      type: ImageChange
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${NAME}-monitor
    annotations:
      description: "Keeps track of changes in the application image"
    labels:
      app: ${NAME}
parameters:
- description: The name assigned to all frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: masu
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: myproject
- description: Initial amount of CPU the Prometheus monitoring container will request.
  displayName: Celery Prometheus Monitor CPU Resource Request
  name: CELERY_MONITOR_CPU_REQUEST
  required: true
  value: 100m
- description: Maximum amount of CPU the Prometheus monitoring container can use.
  displayName: CPU Limit
  name: CELERY_MONITOR_CPU_LIMIT
  required: true
  value: 300m
- description: Initial amount of memory the Prometheus monitoring container will request.
  displayName: Celery Prometheus Monitor Memory Resource Request
  name: CELERY_MONITOR_MEMORY_REQUEST
  required: true
  value: 256Mi
- description: Maximum amount of memory the Prometheus monitoring container can use.
  displayName: Memory Limit
  name: CELERY_MONITOR_MEMORY_LIMIT
  required: true
  value: 512Mi
- description: Initial amount of memory the build container will request.
  displayName: Build Memory Resource Request
  name: BUILD_MEMORY_REQUEST
  required: true
  value: 512Mi
- description: Maximum amount of memory the build container can use.
  displayName: Build Memory Limit
  name: BUILD_MEMORY_LIMIT
  required: true
  value: 1Gi
- description: The custom PyPi index URL
  displayName: Custom PyPi Index URL
  name: PIP_INDEX_URL
- description: The custom PipEnv PyPi index URL
  displayName: Custom PipEnv PyPi Index URL
  name: PIPENV_PYPI_MIRROR
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/project-koku/masu.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
- description: Set this to the relative path to your project if it is not in the root
    of your repository.
  displayName: Context Directory
  name: CONTEXT_DIR
