kind: Template
apiVersion: v1
metadata:
  name: masu-worker-template
  annotations:
    openshift.io/display-name: "Masu"
    description: "Worker for data ingestion engine for Koku"
    tags: "python,flask"
    iconClass: "icon-python"
    openshift.io/long-description: "This template defines resources needed to run the Masu application, including a build configuration and an application deployment configuration."
    openshift.io/provider-display-name: "Red Hat, Inc."
    openshift.io/documentation-url: "https://koku.readthedocs.io/en/latest/"
labels:
  app: masu
  template: masu-template
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    annotations:
      description: Defines how to build the application
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}-worker
    labels:
      app: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-worker:latest
    resources:
      requests:
        memory: ${BUILD_MEMORY_REQUEST}
      limits:
        memory: ${BUILD_MEMORY_LIMIT}
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: PIP_INDEX_URL
            value: ${PIP_INDEX_URL}
          - name: PIPENV_PYPI_MIRROR
            value: ${PIPENV_PYPI_MIRROR}
          - name: ENABLE_PIPENV
            value: "true"
          - name: APP_CONFIG
            valueFrom:
              configMapKeyRef:
                name: ${NAME}
                key: app-config
                optional: false
          - name: APP_HOME
            valueFrom:
              configMapKeyRef:
                name: ${NAME}
                key: app-home
          - name: APP_MODULE
            valueFrom:
              configMapKeyRef:
                name: ${NAME}
                key: app-module
        from:
          kind: ImageStreamTag
          name: python-36-centos7:latest
          namespace: ${NAMESPACE}
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    annotations:
      description: Defines how to deploy the celery workers
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}-worker
    labels:
      app: ${NAME}
  spec:
    replicas: ${CELERY_WORKER_REPLICAS}
    selector:
      name: ${NAME}-worker
    resources:
      requests:
        cpu: ${CELERY_WORKER_CPU_REQUEST}
        memory: ${CELERY_WORKER_MEMORY_REQUEST}
      limits:
        cpu: ${CELERY_WORKER_CPU_LIMIT}
        memory: ${CELERY_WORKER_MEMORY_LIMIT}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${NAME}-worker
        name: ${NAME}-worker
      spec:
        containers:
        - name: ${NAME}-worker
          image: ${NAME}-worker
          command:
            - /bin/bash
            - -c
            - >
              PYTHONPATH=. scl enable rh-python36 --
              celery -A masu.celery.worker worker -E -l $LOG_LEVEL -Q $WORKER_QUEUES
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: ${DATABASE_SERVICE_NAME}
                  optional: false
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: ${DATABASE_SERVICE_NAME}
                  optional: false
            - name: MASU_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: masu-secret-key
                  name: ${NAME}
                  optional: false
            - name: DATABASE_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}
                  key: database-engine
                  optional: false
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}
                  key: database-name
                  optional: false
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}
                  key: postgres-sql-service-host
                  optional: false
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}
                  key: postgres-sql-service-port
                  optional: false
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}
                  key: rabbitmq-host
                  optional: false
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}
                  key: log-level
                  optional: false
            - name: WORKER_QUEUES
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}
                  key: worker-queues
                  optional: false
            - name: SCHEDULE_CHECK_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}
                  key: schedule-check-interval
                  optional: false
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: aws-access-key-id
                  name: ${NAME}
                  optional: false
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: aws-secret-access-key
                  name: ${NAME}
                  optional: false
            - name: REMOVE_EXPIRED_REPORT_DATA_ON_DAY
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}
                  key: remove-expired-data-on-day
                  optional: false
            - name: REMOVE_EXPIRED_REPORT_UTC_TIME
              valueFrom:
                configMapKeyRef:
                  name: ${NAME}
                  key: remove-expired-data-utc-time
                  optional: false
          resources:
            requests:
              cpu: ${CELERY_WORKER_CPU_REQUEST}
              memory: ${CELERY_WORKER_MEMORY_REQUEST}
            limits:
              cpu: ${CELERY_WORKER_CPU_LIMIT}
              memory: ${CELERY_WORKER_MEMORY_LIMIT}
          volumeMounts:
          - mountPath: /var/tmp/masu/
            name: ${NAME}-worker-data
        volumes:
        - name: ${NAME}-worker-data
          persistentVolumeClaim:
            claimName: ${NAME}-worker-data
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - ${NAME}-worker
        from:
          kind: ImageStreamTag
          name: ${NAME}-worker:latest
      type: ImageChange
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${NAME}-worker
    annotations:
      description: "Keeps track of changes in the application image"
    labels:
      app: ${NAME}
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    labels:
      app: ${NAME}
      template: ${NAME}-template
    name: ${NAME}-worker-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
parameters:
- description: The name assigned to all frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: masu
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: myproject
- description: Number of Celery Workers to create
  displayName: Celery Worker Replicas
  name: CELERY_WORKER_REPLICAS
  required: true
  value: '1'
- description: Initial amount of memory the Flower container will request.
  displayName: Celery Worker Memory Request
  name: CELERY_WORKER_MEMORY_REQUEST
  required: true
  value: 1Gi
- description: Maximum amount of memory the Flower container can use.
  displayName: Celery Worker Memory Limit
  name: CELERY_WORKER_MEMORY_LIMIT
  required: true
  value: 1Gi
- description: Initial amount of CPU the Flower container will request.
  displayName: Celery Worker CPU Request
  name: CELERY_WORKER_CPU_REQUEST
  required: true
  value: '500m'
- description: Maximum amount of CPU the Flower container can use.
  displayName: Celery Worker CPU Limit
  name: CELERY_WORKER_CPU_LIMIT
  required: true
  value: '1'
- description: Initial amount of memory the build container will request.
  displayName: Build Memory Request
  name: BUILD_MEMORY_REQUEST
  required: true
  value: 512Mi
- description: Maximum amount of memory the build container can use.
  displayName: Build Memory Limit
  name: BUILD_MEMORY_LIMIT
  required: true
  value: 1Gi
- description: The custom PyPi index URL
  displayName: Custom PyPi Index URL
  name: PIP_INDEX_URL
- description: The custom PipEnv PyPi index URL
  displayName: Custom PipEnv PyPi Index URL
  name: PIPENV_PYPI_MIRROR
- description: Github trigger secret.  A difficult to guess string encoded as part
    of the webhook URL.  Not encrypted.
  displayName: GitHub Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
- displayName: Database Service Name
  name: DATABASE_SERVICE_NAME
  required: true
  value: koku-pgsql
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/project-koku/masu.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
- description: Set this to the relative path to your project if it is not in the root
    of your repository.
  displayName: Context Directory
  name: CONTEXT_DIR
- displayName: Volume Capacity
  description: Volume space available for shared files, e.g. 512Mi, 2Gi
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi
